accepted = [
    "Apache-2.0",
    "MIT",
    "Unicode-3.0",
    "ISC",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "OpenSSL",
    "Apache-2.0 WITH LLVM-exception",
    "Zlib",
    "CDLA-Permissive-2.0",
]
