FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

RUN cat .env

CMD ["sh", "-c", "echo yes | cocoindex main.py setup && cocoindex main.py update && python main.py"]
