"""Data models for Conversation-to-Knowledge pipeline."""

from __future__ import annotations

import re as _re
from dataclasses import dataclass

import cocoindex as coco
import pydantic

# ---------------------------------------------------------------------------
# Context keys (shared across modules)
# ---------------------------------------------------------------------------

LLM_MODEL = coco.ContextKey[str]("llm_model")


# ---------------------------------------------------------------------------
# SurrealDB entity models (dataclasses for declare_record)
# ---------------------------------------------------------------------------


@dataclass
class Session:
    id: int  # Generated by IdGenerator
    youtube_id: str
    name: str
    transcript: str
    description: str | None = None
    date: str | None = None


@dataclass
class Person:
    id: str  # Canonical name used directly as ID
    name: str


@dataclass
class Tech:
    id: str  # Name used directly as ID
    name: str


@dataclass
class Org:
    id: str  # Name used directly as ID
    name: str


@dataclass
class Statement:
    id: int  # Generated by IdGenerator
    statement: str


# ---------------------------------------------------------------------------
# LLM extraction models (Pydantic, for instructor)
# ---------------------------------------------------------------------------


@coco.unpickle_safe
class SpeakerIdentification(pydantic.BaseModel):
    """Maps a diarization label to a real person name."""

    label: str  # e.g. "A", "B"
    name: str  # Full canonical name


@coco.unpickle_safe
class SessionMetadata(pydantic.BaseModel):
    """LLM output from Step 1: session metadata + speaker mapping."""

    name: str
    description: str | None = None
    date: str | None = None
    speakers: list[SpeakerIdentification]


@coco.unpickle_safe
class RawStatement(pydantic.BaseModel):
    """A thematic claim or statement made during the session."""

    statement: str
    speakers: list[str]  # Names of persons who made the statement
    involved_persons: list[str] = []
    involved_techs: list[str] = []
    involved_orgs: list[str] = []


@coco.unpickle_safe
class StatementExtraction(pydantic.BaseModel):
    """LLM output from Step 2: statements with involved entities."""

    statements: list[RawStatement]


# ---------------------------------------------------------------------------
# Internal transfer types
# ---------------------------------------------------------------------------


@coco.unpickle_safe
@dataclass
class Utterance:
    """A single speaker-labeled utterance from diarized transcription."""

    speaker: str  # Diarization label, e.g. "A", "B"
    text: str


@coco.unpickle_safe
@dataclass
class SessionTranscript:
    """Carries structured utterances and yt-dlp metadata."""

    utterances: list[Utterance]
    yt_channel: str
    yt_title: str
    yt_description: str | None
    yt_upload_date: str | None


@coco.unpickle_safe
@dataclass
class IdentifiedStatement:
    """A statement with its generated ID, for carrying through the pipeline."""

    id: int
    raw: RawStatement


@coco.unpickle_safe
@dataclass
class SessionRawEntities:
    """Raw entities from a single session, for entity resolution."""

    session_id: int
    persons: list[str]
    statements: list[IdentifiedStatement]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def resolve_canonical(name: str, dedup: dict[str, str | None]) -> str:
    """Chase dedup chains to find the canonical name."""
    while dedup.get(name) is not None:
        name = dedup[name]  # type: ignore[assignment]
    return name


_SPEAKER_LABEL_RE = _re.compile(r"^\(?speaker\s+[a-z]\)?$", _re.IGNORECASE)


def is_speaker_label(name: str) -> bool:
    """Check if a name is a speaker diarization label (e.g. 'Speaker A', '(Speaker B)')."""
    return _SPEAKER_LABEL_RE.match(name.strip()) is not None
