"""Data models for Conversation-to-Knowledge pipeline."""

from __future__ import annotations

import re as _re
from dataclasses import dataclass, field

import cocoindex as coco
import pydantic

# ---------------------------------------------------------------------------
# Context keys (shared across modules)
# ---------------------------------------------------------------------------

LLM_MODEL = coco.ContextKey[str]("llm_model")
RESOLUTION_LLM_MODEL = coco.ContextKey[str]("resolution_llm_model")


# ---------------------------------------------------------------------------
# Entity type configuration
# ---------------------------------------------------------------------------

PERSON_ENTITY_NAME = "person"


@dataclass
class EntityTypeConfig:
    """Configuration for a named entity type (person, tech, org, ...)."""

    name: str
    llm_description: str  # Injected into the extraction prompt
    llm_examples: list[str] = field(default_factory=list)  # Canonical name examples


ENTITY_TYPES: list[EntityTypeConfig] = [
    EntityTypeConfig(
        name=PERSON_ENTITY_NAME,
        llm_description=(
            "Real people, using Wikipedia-style full names. "
            "Only include people you can confidently identify with their full name — "
            "omit anyone you cannot identify. Do not guess."
        ),
        llm_examples=["Lex Fridman", "Sam Altman", "Franklin D. Roosevelt"],
    ),
    EntityTypeConfig(
        name="tech",
        llm_description="Technologies, tools, frameworks, and concepts.",
        llm_examples=[
            "Python (programming language)",
            "Large language model",
            "ChatGPT",
        ],
    ),
    EntityTypeConfig(
        name="org",
        llm_description="Organizations and companies, using their canonical names.",
        llm_examples=["OpenAI", "Google DeepMind", "US Department of Education"],
    ),
]


# ---------------------------------------------------------------------------
# SurrealDB entity models (dataclasses for declare_record)
# ---------------------------------------------------------------------------


@dataclass
class Session:
    id: int  # Generated by IdGenerator
    youtube_id: str
    name: str
    transcript: str
    description: str | None = None
    date: str | None = None


@dataclass
class Entity:
    """Generic named entity node (person, tech, org). Name is used as ID."""

    id: str
    name: str


@dataclass
class Statement:
    id: int  # Generated by IdGenerator
    statement: str


# ---------------------------------------------------------------------------
# LLM extraction models (Pydantic, for instructor)
# ---------------------------------------------------------------------------


@coco.unpickle_safe
class SpeakerIdentification(pydantic.BaseModel):
    """Maps a diarization label to a real person name."""

    label: str  # e.g. "A", "B"
    name: str  # Full canonical name


@coco.unpickle_safe
class SessionMetadata(pydantic.BaseModel):
    """LLM output from Step 1: session metadata + speaker mapping."""

    name: str
    description: str | None = None
    date: str | None = None
    speakers: list[SpeakerIdentification]


@coco.unpickle_safe
class RawStatement(pydantic.BaseModel):
    """A thematic claim or statement made during the session."""

    statement: str
    speakers: list[str]  # Names of persons who made the statement
    mentioned_person: list[str] = []
    mentioned_tech: list[str] = []
    mentioned_org: list[str] = []


@coco.unpickle_safe
class StatementExtraction(pydantic.BaseModel):
    """LLM output from Step 2: statements with involved entities."""

    statements: list[RawStatement]


# ---------------------------------------------------------------------------
# Internal transfer types
# ---------------------------------------------------------------------------


@coco.unpickle_safe
@dataclass
class Utterance:
    """A single speaker-labeled utterance from diarized transcription."""

    speaker: str  # Diarization label, e.g. "A", "B"
    text: str


@coco.unpickle_safe
@dataclass
class SessionTranscript:
    """Carries structured utterances and yt-dlp metadata."""

    utterances: list[Utterance]
    yt_channel: str
    yt_title: str
    yt_description: str | None
    yt_upload_date: str | None


@coco.unpickle_safe
@dataclass
class IdentifiedStatement:
    """A statement with its generated ID, for carrying through the pipeline."""

    id: int
    raw: RawStatement


@coco.unpickle_safe
@dataclass
class SessionRawEntities:
    """Raw entities from a single session, for entity resolution."""

    session_id: int
    # Maps entity type name → session-level participants (e.g. "person" → identified speakers).
    # Statement-level entities are accessed directly via IdentifiedStatement.raw.
    raw_entities: dict[str, list[str]]
    statements: list[IdentifiedStatement]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def resolve_canonical(name: str, dedup: dict[str, str | None]) -> str:
    """Chase dedup chains to find the canonical name."""
    while dedup.get(name) is not None:
        name = dedup[name]  # type: ignore[assignment]
    return name


_SPEAKER_LABEL_RE = _re.compile(r"^\(?speaker\s+[a-z]\)?$", _re.IGNORECASE)


def is_speaker_label(name: str) -> bool:
    """Check if a name is a speaker diarization label (e.g. 'Speaker A', '(Speaker B)')."""
    return _SPEAKER_LABEL_RE.match(name.strip()) is not None
